feat: Added BG MANAGE step to Envgene Instance Pipeline (#958)

diff --git a/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml b/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml
--- a/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml
+++ b/github_workflows/instance-repo-pipeline/.github/workflows/Envgene.yml
@@ -79,6 +79,7 @@ jobs:
     runs-on: ${{ vars.GH_RUNNER_TAG_NAME || 'ubuntu-22.04'  }}
     outputs:
       env_matrix: ${{ steps.matrix-generator.outputs.env_matrix }}
+      BG_MANAGE: ${{ env.BG_MANAGE }}
       ENV_TEMPLATE_TEST: ${{ env.ENV_TEMPLATE_TEST }}
       ENV_SPECIFIC_PARAMETERS: ${{ env.ENV_SPECIFIC_PARAMETERS }}
       ENV_TEMPLATE_NAME: ${{ env.ENV_TEMPLATE_NAME }}
@@ -179,6 +180,25 @@ jobs:
 
       - name: Create env file for container
         run: env > .env.container
+
+      ### BG MANAGE ###
+      - name: BG Manage
+        if: needs.process_environment_variables.outputs.BG_MANAGE == 'true'
+        env:
+          FULL_ENV_NAME: ${{ matrix.environment }}
+        run: |
+          docker run --rm -v ${{ github.workspace }}:${{ env.CI_PROJECT_DIR }} -w ${{ env.CI_PROJECT_DIR }} -e GITHUB_TOKEN -e FULL_ENV_NAME -e CI_PROJECT_DIR --user root --env-file .env.container --user root -e HOME=/root \
+          ${{ env.DOCKER_IMAGE_NAME_ENVGENE }}:${{ env.DOCKER_IMAGE_TAG_ENVGENE }} \
+          bash -c "
+            source /module/venv/bin/activate
+
+            echo "Executing BG Manage..."
+            if ! python /scripts/bg_manage/bg_manage.py; then
+              echo "BG Manage failed with exit code $?"
+              exit 1
+            fi
+          "
+      ##########################
 
       ### GENERATE INVENTORY ###
       - name: Generate Inventory
