feat: Add the GSF Instance package (#861)
Added logic for GSF

diff --git a/.github/actions/build-gsf-instance/action.yml b/.github/actions/build-gsf-instance/action.yml
--- a/.github/actions/build-gsf-instance/action.yml
+++ b/.github/actions/build-gsf-instance/action.yml
@@ -52,6 +52,9 @@ runs:
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
+      with:
+        token: ${{ inputs.github-token }}
+        fetch-depth: 0
 
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
@@ -69,6 +72,40 @@ runs:
     - name: Generate Docker tags
       id: tags
       uses: ./.github/actions/generate-docker-tags
+
+    - name: Copy config.schema.json to git_hooks
+      shell: bash
+      run: |
+        mkdir -p "gsf_packages/envgene_instance_project/git-system-follower-package/scripts/templates/default/{{ cookiecutter.gsf_repository_name }}/git_hooks"
+        cp schemas/config.schema.json \
+          "gsf_packages/envgene_instance_project/git-system-follower-package/scripts/templates/default/{{ cookiecutter.gsf_repository_name }}/git_hooks/config.schema.json"
+
+    - name: Update history.log
+      shell: bash
+      run: |
+        COOKIECUTTER_DIR="gsf_packages/envgene_instance_project/git-system-follower-package/scripts/templates/default/{{ cookiecutter.gsf_repository_name }}"
+        HISTORY_FILE="gsf_packages/envgene_instance_project/git-system-follower-package/scripts/templates/default/{{ cookiecutter.gsf_repository_name }}/history.log"
+
+        # Run Python script to update history.log
+        python3 ./.github/actions/build-gsf-instance/update_history.py \
+          "$COOKIECUTTER_DIR" \
+          "$HISTORY_FILE"
+
+    - name: Commit and push changes
+      shell: bash
+      run: |
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "github-actions[bot]@users.noreply.github.com"
+        git remote set-url origin https://x-access-token:${{ inputs.github-token }}@github.com/${GITHUB_REPOSITORY}.git
+
+        BRANCH_NAME=${GITHUB_REF#refs/heads/}
+        BRANCH_NAME=${BRANCH_NAME#refs/tags/}
+
+        git add -A
+        if ! git diff --quiet --cached; then
+          git commit -m "chore: Update package files [skip ci]"
+          git push origin HEAD:"${BRANCH_NAME}" || echo "Failed to push changes"
+        fi
 
     - name: Extract metadata (tags, labels) for Docker
       id: meta
